### ISSUE TITLE
Liquibase History command fails assuming it is an OS command

### ISSUE THREAD

**Issue by szandany** [liquibase/docker#140]
When testing Liquibase Docker image with GitHub Actions, it appears that unlike other commands, the Liquibase History command fails.
It looks like the Liquibase History command is logically being considered as a Linux OS history command first before being considered as a Liquibase command.

**Steps to reproduce**
1. Set a GitHub workflow with Liquibase Docker image and a job with the history command.
```
  Build_Job:
    runs-on: ubuntu-latest
    environment: 
      name: DEV

    steps:
    - uses: actions/checkout@v2
    
    - name: Running the history command
      uses: docker://liquibase/liquibase:snowflake
      with:
        args: history
````

2. Run the workflow.

**Actual results**
`
Run docker://liquibase/liquibase:snowflake
/usr/bin/docker run --name liquibaseliquibasesnowflake_963cf4 --label e28490 --workdir /github/workspace --rm -e LB_VERSION -e ***_PRO_LICENSE_KEY -e ***_COMMAND_URL -e ***_COMMAND_USERNAME -e ***_COMMAND_PASSWORD -e ***_COMMAND_CHANGELOG_FILE -e ***_HUB_API_KEY -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Snowflake/Snowflake":"/github/workspace" liquibase/liquibase:snowflake history
/liquibase/docker-entrypoint.sh: line 10: exec: history: not found
`
