### ISSUE TITLE
Connecting to Oracle requires correct TimeZone

### ISSUE THREAD

**Issue by FukoH** [liquibase/docker#150]
Timezone is not set inside docker container so that I cannot connect to oracle directly. An error of ORA-01882 occurs. May be  some option to initialize container timezone is needed.

**Comment by sfat** [comment]
The containers seems to be defaulting to GMT, so in order to match your timezone, you need to pass the `TZ` environment variable to override the default timezone as follows:

docker run command:
```
docker run [...] -e TZ=Australia/Brisbane (this is just an example)
```
docker compose configuration:

```
services:
  liquibase:
    image: liquibase/liquibase
    environment:
      - TZ=Australia/Brisbane
    command: [...configuration here.]
```
