### ISSUE TITLE
ERROR liquibase.integration.commandline.Main  when using command in docker-compose

### ISSUE THREAD

**Issue by Fixed-cloud** [liquibase/docker#8]
I get this error when using this in docker-compose
````
liquibase_dev | 11:08:52.578 [main] DEBUG liquibase.resource.ClassLoaderResourceAccessor - Opening jar:file:/liquibase/liquibase.jar!/liquibase.build.properties as liquibase.build.properties
liquibase_dev | 11:08:52.626 [main] INFO liquibase.integration.commandline.Main - Starting Liquibase at Mon, 04 May 2020 11:08:52 UTC (version 3.8.9 #73 built at Mon Apr 06 09:32:58 UTC 2020)
liquibase_dev | 11:08:52.626 [main] WARN liquibase.integration.commandline.Main - To display the help, please pass the '--help' option on the command line.
liquibase_dev | 11:08:52.627 [main] ERROR liquibase.integration.commandline.Main - Unexpected error running Liquibase: Unexpected value 'java' (options must start with a '--')
liquibase_dev | 11:08:52.627 [main] ERROR liquibase.integration.commandline.Main - For more information, please use the --logLevel flag
liquibase_dev | 11:08:52.645 [main] ERROR liquibase.integration.commandline.Main - Unexpected error running Liquibase: Unexpected value 'java' (options must start with a '--')
liquibase_dev | liquibase.exception.CommandLineParsingException: Unexpected value 'java' (options must start with a '--')
liquibase_dev |      at liquibase.integration.commandline.Main.parseOptions(Main.java:1109)
liquibase_dev |      at liquibase.integration.commandline.Main.run(Main.java:253)
liquibase_dev |      at liquibase.integration.commandline.Main.main(Main.java:162)
liquibase_dev exited with code 255
````

my liquibase setting:
````
  liquibase:
    container_name: liquibase_dev
    image: liquibase/liquibase
    command:  java -jar liquibase.jar --logLevel=DEBUG  --changeLogFile=changelog.postgresql.sql generateChangeLog
    depends_on:
      - postgres
    networks:
      slate_network:
          ipv4_address: 172.28.1.2
````

This is not even picking up liquibase.properties there in my project's root directory where docker-compose.yml is.
Please Help!
